### ISSUE TITLE
manifest translation' typo

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/chtickynotes_ynh#4]
hi, can you please fix your manifest?
there is two "en" keys:

                    "en": "Choose a domain for ChtickyNotes",
                    "en": "Choisissez un domaine pour ChtickyNotes"

thanks for your help

**Comment by M5oul** [comment]
Wow, ugly!
If the maintainer won't change that. We will have to remove the app from community list.
Or, we could fork it on YunoHost-Apps organization and fix that locale issue.
I prefer second solution, as I am using this app.

**Comment by Jibec** [comment]
it's just a typo, no big deal :)
We'll wait for a fix from @chtixof

**Comment by chtixof** [comment]
Done
