### ISSUE TITLE
Is this app still maintained ? (No: a new maintener is needed)

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/chtickynotes_ynh#7]

**Comment by chtixof** [comment]
Hello. I created it. But I have not used it for years. And I do not intend to maintain it for now. However, the community may maintain it.

**Comment by lapineige** [comment]
Ok :)

Could you merge my PR then ?
And maybe give me write permission on this repo ? I'm not going to maintain it, but I can still do some minor improvements, if I have some free time :)

**Comment by ericgaspar** [comment]
Back to life with #9
